# Generated by Django 3.0.8 on 2020-08-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_auto_20200808_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
