# Generated by Django 3.0.8 on 2020-08-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_upload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
